<?php
return [
    'LOAN_FLAG'=>['A'=>'Active','C'=>'Completed','H'=>'Hold'],
    'TAX_FLAG' => ['TA','NA','NT','AI','TR','BC','ND','DD','NN','BD','GD','SE','SEA','SS','SR','SRA'],
    'TAX_FLAG_NAME' => ['Taxable Benefit',
                        'Non-Taxable Benefit',
                        'Notional Allowance',
                        'Adjust Taxable Income',
                        'Tax Adjustment',
                        'Bank Credit',
                        'After Tax Deduction',
                        'Before Tax Deduction',
                        'Notional Deduction',
                        'Bank Deduction',
                        'Gratuity Deduction',
                        'Employee Default Super',
                        'Employee Additional Super',
                        'Super Sacrifice',
                        'Employer Default Super',
                        'Employer Additional Super'],
    'EMP_FLAG'=>['0'=>'N/A','A'=>'Active','L'=>'Leave','R'=>'Resigned','T'=>'Terminated'],
    'SPREAD_CODE' => ['1','S','Q','O'],
    'EMP_ESTATUS' => ['Full Time','Part Time','Casual','Probationary','Contractual','Other'],
    'MARITAL_STATUS' => ['Single','Married','Never Married','Widow'],
    'EMPLOYMENT_STATUS' => ['Permanent','Part Time','Casual','Contractual'],
    'EMP_GENDER' => ['Male','Female','Other'],
    'PAY_MODE'=>['C','Q','B'],
    'PAY_MODE_NAME'=>['Cash','Cheque','Bank'],
];
